/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package culminating;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author erhal8376
 */
public class CalculateW extends javax.swing.JFrame {

    /**
     * Creates new form CalculateT
     */
    public CalculateW() {
        //this.i = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        weightGroup = new javax.swing.ButtonGroup();
        benchInput = new javax.swing.JTextField();
        benchLabel = new javax.swing.JLabel();
        squatInput = new javax.swing.JTextField();
        squatLabel = new javax.swing.JLabel();
        deadInput = new javax.swing.JTextField();
        deadLabel = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        weightInput = new javax.swing.JTextField();
        weightLabel = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        lbsButton = new javax.swing.JRadioButton();
        kgButton = new javax.swing.JRadioButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        benchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benchInputActionPerformed(evt);
            }
        });
        benchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                benchInputKeyPressed(evt);
            }
        });

        benchLabel.setText("Bench:");

        squatInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squatInputActionPerformed(evt);
            }
        });
        squatInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                squatInputKeyPressed(evt);
            }
        });

        squatLabel.setText("Squat:");

        deadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadInputActionPerformed(evt);
            }
        });
        deadInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deadInputKeyPressed(evt);
            }
        });

        deadLabel.setText("Deadlift:");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        weightInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightInputActionPerformed(evt);
            }
        });
        weightInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                weightInputKeyPressed(evt);
            }
        });

        weightLabel.setText("Weight:");

        group.add(maleButton);
        maleButton.setText("Male");

        group.add(femaleButton);
        femaleButton.setText("Female");

        weightGroup.add(lbsButton);
        lbsButton.setText("Lbs");

        weightGroup.add(kgButton);
        kgButton.setText("Kg");

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deadLabel)
                            .addComponent(squatLabel)
                            .addComponent(benchLabel)
                            .addComponent(weightLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deadInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(squatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(benchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(calculateButton)
                        .addGap(30, 30, 30)
                        .addComponent(exitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbsButton)
                                .addGap(72, 72, 72)
                                .addComponent(kgButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(femaleButton)
                                .addGap(44, 44, 44)
                                .addComponent(maleButton)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(benchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(benchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(squatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleButton)
                    .addComponent(femaleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kgButton)
                    .addComponent(lbsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(exitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double total;
        
    //output.setText("Calculated total is "+)
    
    private void benchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benchInputActionPerformed

    }//GEN-LAST:event_benchInputActionPerformed

    private void squatInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squatInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_squatInputActionPerformed

    private void deadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadInputActionPerformed

    private void benchInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_benchInputKeyPressed

    }//GEN-LAST:event_benchInputKeyPressed

    private void squatInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_squatInputKeyPressed

    }//GEN-LAST:event_squatInputKeyPressed

    private void deadInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deadInputKeyPressed

    }//GEN-LAST:event_deadInputKeyPressed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double bench = 0;
        double squat = 0;
        double dead = 0;
        double weight = 0;
        
        if(kgButton.isSelected()) {
            weight = Double.parseDouble(weightInput.getText());
            bench = Double.parseDouble(benchInput.getText());
            squat = Double.parseDouble(squatInput.getText());
            dead = Double.parseDouble(deadInput.getText());
        }
        else if(lbsButton.isSelected()) {
            weight = Double.parseDouble(weightInput.getText())/2.205;
            bench = Double.parseDouble(benchInput.getText())/2.205;
            squat = Double.parseDouble(squatInput.getText())/2.205;
            dead = Double.parseDouble(deadInput.getText())/2.205;
        }
        
        total = bench+squat+dead;
        double temp = 0;
        
        double a = Math.pow(weight, 2);
        double b = Math.pow(weight, 3);
        double c = Math.pow(weight, 4);
        double d = Math.pow(weight, 5);
        double e = Math.pow(4.731582, -5);
        double f = Math.pow(9.054, -8);
        double g = Math.pow(7.01863, -6);
        double h = Math.pow(1.291, -8);       
        
        if(femaleButton.isSelected()) {
            temp = 594.31747775582;
            temp -= 27.23842536447*weight;
            temp += 0.82112226871*a;
            temp -= 0.00930733913*b; 
            temp += e*c;
            temp -= f*d;
        }
        
        else if(maleButton.isSelected()) {
            temp = -216.0475144;
            temp += weight*16.2606339;
            temp -= 0.002388645*a; 
            temp -= 0.00113732*b;
            temp += g*c;
            temp -= d*h;
        }
        
        double wilks = 500/temp;
        double score = total*wilks;
        
        output.setText("Your calculated wilks score is: "+Double.toString(score));
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.setVisible(false); // hiding this form
    }//GEN-LAST:event_exitButtonActionPerformed

    private void weightInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightInputActionPerformed

    private void weightInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightInputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField benchInput;
    private javax.swing.JLabel benchLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField deadInput;
    private javax.swing.JLabel deadLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.ButtonGroup group;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JRadioButton kgButton;
    private javax.swing.JRadioButton lbsButton;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel output;
    private javax.swing.JTextField squatInput;
    private javax.swing.JLabel squatLabel;
    private javax.swing.ButtonGroup weightGroup;
    private javax.swing.JTextField weightInput;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
